build:
  publish: dist
  command: npm run build

# Netlify build plugins
plugins:
  # Path to plugin. Can be local relative path or reference to node_modules
  - package: ../netlify-plugin-minify-html/index.js
    config:
      # Builds in which deploy contexts will get minified?
      # [production, deploy-preview, branch-deploy]
      targets:
        - production
        - deploy-preview
        - branch-deploy
      minifierOptions:
        - removeComments: true
        - minifyCSS: true
        - removeEmptyElements: true
